### ISSUE TITLE
[UT2004->UT4] - ONS-Torlan - Distorted map geometry and missing textures

### ISSUE THREAD

**Issue by matty45** [xtremexp/UT4X-Converter#30]
Hello, i was wanting to convert ONS-Torlan from UT2004 so i could mess around with it, however when converted and the t3d pasted in, it looks like this:
![](https://i.imgur.com/JcSYBNO.jpg)

The terrain is not in the right place and some objects seem to have missing textures:
![](https://i.imgur.com/vHka2zl.png)

I followed the conversion instructions closely so im not sure if this is my fault. It would be very much appreciated if you could fix this.

**Comment by xtremexp** [comment]
i don't think that is a bug from converter, i ever had tried this map for terrain conversion and it was pretty good :
![UT4X-Conv-Terrain-UT2004-Dria-WIP](https://user-images.githubusercontent.com/11919600/83156391-a6e12180-a102-11ea-90e8-1ed6e4d1d761.png)

**Comment by xtremexp** [comment]
I've reproduced the issue, it seems the terrain is upside down or maybe have bad rotation.
Setting up a positive Z scale value makes it at least appear correctly even if it's not well positioned:
![image](https://user-images.githubusercontent.com/11919600/209087949-b083eba1-f437-44a0-a518-b967ed02747f.png)
![image](https://user-images.githubusercontent.com/11919600/209088009-a49b0f75-dd2b-48d5-a4eb-d2df94634004.png)

As for materials, converter does not yet convert shaders that why materials.
Will try to see what's wrong for the terrain at least when i'll have some extra time. Ty for reporting issue.

**Comment by xtremexp** [comment]
This terrain issue has been fixed. Ty for reporting.
Here is some test with latest version:
![image](https://user-images.githubusercontent.com/11919600/214346517-6f74f06a-d55d-43ff-83cb-1a17ef6c8e72.png)
