### ISSUE TITLE
Maven issue 1.6.0

### ISSUE THREAD

**Issue by therealnevax** [xtremexp/UT4X-Converter#35]
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (create-package) on project UT4X-Converter: Command execution failed.

Wont process the UT4X-Conveter command line "clean install -e"

any ideas would be helpful for this IntelliJ IDEA issue I am having. I've even deleted the 1.6.0 out of the repository and even after it reloads it, it still doesnt work.

**Comment by xtremexp** [comment]
Hi ! Sorry for late reply, will have a look when i'll have some time.

**Comment by xtremexp** [comment]
I've fixed issue with jpackager file not found.
Try again but using jdk14 or more. I've tested it should be ok.
