### ISSUE TITLE
No import options

### ISSUE THREAD

**Issue by DrDv8** [xtremexp/UT4X-Converter#55]
Does this work with ute4 ver.4.15.0 ? I saw your youtube video on converting ut (1999) to ut4 (2015), everything works great and I can follow you till you import into ute4. I don't have the option to import only to import into level, so i pick that option and navigate to where the converted map is. But the map is .t3d and my ute4 wants .fbx or .obj. How do I fix this?

**Comment by xtremexp** [comment]
Hello, youtube video was made using older unreal engine version.
At that time, the .t3d option was available and shown. Now it's hidden but still available.
You have to key in "*.*" in file filter, press enter then the .t3d files will show.
![image](https://user-images.githubusercontent.com/11919600/151321001-a7f8cf86-6de4-4af1-b92d-1ba39eac10cb.png)


You can also just open the .t3d file in a text editor copy/paste all into editor.
