### ISSUE TITLE
UT-Converter not working with UTF-16 t3d files

### ISSUE THREAD

**Issue by Sagatt** [xtremexp/UT4X-Converter#78]
If possible please investigate, this is a .t3d, i've converted onto ".txt" so i could upload it here.

[zoneoneleveltwo.txt](https://github.com/xtremexp/UT4X-Converter/files/10532242/zoneoneleveltwo.txt)

**Comment by xtremexp** [comment]
This file is encoded in UTF-16 which converter could not read properly. (usually reads UTF-8 files)
This has been fixed with 1.4.9 version.
