### ISSUE TITLE
can you convert back an UT3 map to UT2004 or UT99 ?

### ISSUE THREAD

**Issue by dragonlordelite** [xtremexp/UT4X-Converter#88]
Hi !! i made a good map for UT3 + there are bots places to guard when giving orders..

i would like to know if it's possible to convert down a UT3 map ? or up for last UT ?

Thanx for your help !!

**Comment by xtremexp** [comment]
There is no plan to backward port UT3 maps to UT2004/UT99 for now since it would take huge time for very very few guys.
